trigger:
  branches:
    include:
      - latest
  tags:
    include:
      - v*

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      sudo apt-get install -y texlive-full
      sudo apt-get install -y latexmk
    displayName: install
  - script: |
      make
    displayName: build
  - task: GitHubRelease@0
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
    inputs:
      gitHubConnection: aplqo
      repositoryName: aplqo/$(repository_name)
      target: '$(Build.SourceVersion)'
      tagSource: 'auto'
      action: create
      assets: ./*.pdf
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: ./*.pdf
